# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
#en:
#  languageCode: "en"
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
ja:
  languageCode: ja
  contentDir: content/ja
  title: Takahashi Mayu
  params:
    description: 
  menu:
    main:
      - name: 髙橋 茉優
        url: '#about'
        weight: 1
